double Monday = 21.5;
double Tuesday = 23.7;
double Wednesday = 19.6;
double Thursday = 22.5;
double Friday = 25.3; 
double Saturday = 21.7;
double Sunday = 18.9;
double D1 = Tuesday-Monday;
double D2 = Wednesday - Tuesday;
double D3 = Thursday - Wednesday;
double D4 = Friday - Thursday;
double D5 = Saturday - Friday;
double D6 = Sunday - Saturday;
Console.WriteLine(D1);
Console.WriteLine(D2);
Console.WriteLine(D3);
Console.WriteLine(D4);
Console.WriteLine(D5);
Console.WriteLine(D6);